from django.urls import path
from create_user import views
from rest_framework.urlpatterns import format_suffix_patterns
from django.conf.urls import  url


urlpatterns = [
    path('', views.Users_View.as_view(), name='users'),
    path('users_list/', views.User_List.as_view()),
    path('location_list/',views.User_Insert_Location.as_view()),
    path('erp_calendar/',views.Erp_Calendar.as_view()),
    path('erp_calendar_list/',views.Erp_Calendar_List.as_view()),
    path('erp_calendar_event/',views.Erp_Calendar_Event.as_view()),
    path('role_based_auth/',views.Role_Based_Auth.as_view()),
    path('delete_event/',views.Delete_Event_Api.as_view()),
    path('customers_erp/',views.Customers_Data.as_view()),
    path('customers_erp_all/',views.Customers_Data_All.as_view()),
    path('customer_detail/',views.Customer_details.as_view()),
    path('address_detail/',views.Address_details.as_view()),
    path('image_upload/',views.Image_Upload.as_view()),
    path('cover_image_upload/',views.Cover_Image_Upload.as_view()),
    path('lead_detail/',views.Lead_details.as_view()),
    path('contact_detail_single/',views.Contact_Details.as_view()),
    path('crud_operation/',views.DoctypeCRUD.as_view()),
    path('comments/',views.CommentSection.as_view()),
    path('reply/',views.ReplySection.as_view()),
    path('contact_detail_customer/',views.Contact_Details_Customer.as_view()),
    path('delete_customer_detail/',views.Delete_Customer_details.as_view()),
    path('delete_opportunity/',views.Delete_Opportunity.as_view()),
    path('customer_lead_details/',views.Customer_Leads.as_view()),
    path('update_review/',views.Update_Review.as_view()),
    path('get_sales_item/',views.Get_SalesOrder.as_view()),
    path('contact_us/',views.ContactUs.as_view()),
    path('insert_lead/',views.Insert_Lead_.as_view()),
    path('insert_issue/',views.InsertIssue.as_view()),
    path('get_benefits/',views.Get_Cateogary.as_view()),
    path('testimonials/',views.Testimonial.as_view()),
    path('like_getter/',views.Like_Getter.as_view()),
    path('user_like_getter/',views.User_Like_Getter.as_view()),
    path('get_user_uploaded_image/',views.Get_User_Uploaded_Images.as_view()),
    path('get_follow_list/',views.Following_list.as_view()),
    path('search_user/',views.Search_User.as_view()),
    path('get_follow_list_all/',views.GetFollowList.as_view()),
    path('search_tag/',views.At_TheRate.as_view()),
    path('user_post/',views.User_POST.as_view()),
    path('coupon_list/',views.Coupon_List.as_view()),
    path('CouponCode/',views.CouponCode.as_view()),
    path('youtubevid/',views.YouTubeVid.as_view()),
    path('follow_count/',views.Follow_Count.as_view()),
    path('forgotPassword/',views.ForgotPassword.as_view()),
    path('insert_supplier/',views.SupplierInsert.as_view()),
    path('follower/',views.Follower_Module.as_view()),
    
    path('delete_wishlist/',views.DeleteWishlist.as_view()),
    path('check_pincode/',views.CheckPincode.as_view()),
    path('wishlist/',views.WishList.as_view()),
    path('contact_details/',views.Contact_Data.as_view()),
    path('to_do_list/',views.ToDo.as_view()),
    path('to_do_update/',views.ToDo_Single_Item.as_view()),
    path('to_do_delete/',views.ToDoDelete.as_view()),
    path('get_location_api/',views.Get_Location_Api.as_view()),
    path('filter_data_doctype/',views.Filter_Data_Doctype.as_view()),
    path('get_filter_map_data/',views.Filter_Map_Data.as_view()),
    url(r'^map_view/',views.display_map,name='map_view'),
    url(r'^erp_user_login/',views.erp_user_login,name='erp_user_login'),
    url(r'^login/',views.login,name='login'),
    url(r'^email_sign_up/',views.email_sign_up,name='email_sign_up'),
    url(r'^get_address/',views.get_address,name='get_address'),
    url(r'^add_address/',views.add_address,name='add_address'),
    url(r'^add_to_cart/',views.add_to_cart,name='add_to_cart'),
    url(r'^get_cart_item/',views.get_cart_item,name='get_cart_item'),
    url(r'^add_to_quotation/',views.add_to_quotation,name='add_to_quotation'),
    url(r'^update_quotation/',views.update_quotation,name='update_quotation'),
    url(r'^get_sales_invoice/',views.get_sales_invoice,name='get_sales_invoice'),
    url(r'^update_address/',views.update_address,name='update_address'),
    url(r'^delete_address/',views.delete_address,name='delete_address'),
    url(r'^erp_user_login_covid/',views.erp_user_login_covid,name='erp_user_login_covid'),
    url(r'^item_retrieval_api/',views.item_retrieval_api2,name='item_retrieval_api2'),
    url(r'^item_detail/',views.item_detail,name='item_detail'),
    url(r'^item_filter/',views.item_filter,name='item_filter'),
    url(r'^single_item_detail/',views.single_item_detail,name='single_item_detail'),
    url(r'^products/popular/',views.popular_api,name='popular_api'),
    url(r'^brands/',views.brands,name='brands'),
    url(r'^item/',views.item,name='item'),
    url(r'^get_item_details/',views.get_item_details,name='get_item_details'),
    url(r'^get_tax_information/',views.get_tax_information,name='get_tax_information'),
    url(r'^products/',views.products,name='products'),
    url(r'^brands_list/',views.brands_list,name='brands_list'),
    url(r'^insert_temprature/',views.insert_temprature,name='insert_temprature'),
    url(r'^insert_timesheet/',views.insert_timesheet,name='insert_timesheet'),
    url(r'^insert_profile/',views.insert_profile,name='insert_profile'),
    url(r'^insert_lead_user/',views.insert_lead_user,name='insert_lead_user'),
    url(r'^insert_india_mart_lead/',views.insert_india_mart_lead,name='insert_india_mart_lead'),
    url(r'^googlecalendar/',views.googlecalendar,name='googlecalendar'),
    url(r'^update_google_calendar/',views.update_google_calendar,name='update_google_calendar'),
    url(r'^update_google_calendar2/',views.update_google_calendar2,name='update_google_calendar2'),
    url(r'^update_erp_calendar/',views.update_erp_calendar,name='update_erp_calendar'),
    url(r'^update_erp_calendar2/',views.update_erp_calendar2,name='update_erp_calendar2'),
    url(r'^insert_attendance/',views.Insert_Attendance,name='insert_attendance'),
    url(r'^itemSearchApi/',views.ItemSearchAPI.as_view(),name='itemsearch'),
    path('profile/',views.Profile.as_view()),
    path('ratings/',views.Rating.as_view()),
    path('UsedCoupon/',views.UsedCoupon.as_view()),
    path('website_slider/',views.Website_Slider.as_view()),
    path('single_opp_detail/',views.Single_Opp_details.as_view()),
    path('territories/',views.Get_Territories.as_view()),
    path('items/',views.Get_Item.as_view()),
    path('user_list_erp/',views.Get_User.as_view()),
    path('designation_list/',views.Designation_List.as_view()),
    path('opp_detail/',views.Opp_Details.as_view()),
    path('insert_erp_user/',views.Insert_Erp_User.as_view()),
    path('contact_detail_single/',views.Contact_Details.as_view()),
    path('delete_customer_detail/',views.Delete_Customer_details.as_view()),
    path('integerate_facebook_leads/',views.FB_Leads.as_view()),
    path('insert_sales_invoice/',views.Sales_Invoice.as_view()),
    path('get_lead_emm/',views.Get_Lead_Emm.as_view()),
    path('get_address_detail/',views.Get_Address_details.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)