# Generated by Django 2.2 on 2019-04-30 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvents',
            fields=[
                ('event_id', models.TextField(blank=True, default='', null=True)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('lead_name', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('lead_series', models.CharField(default='', max_length=50)),
                ('event_bit', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(default=0.0, max_length=20)),
                ('longitude', models.CharField(default=0.0, max_length=20)),
                ('email_id', models.EmailField(default='', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('user_id', models.IntegerField(default=0)),
                ('logged_in', models.BooleanField(default=False)),
            ],
        ),
    ]
