# Generated by Django 2.2 on 2019-07-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
