# Generated by Django 2.2 on 2019-11-13 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('create_user', '0002_location_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
