# Generated by Django 2.2 on 2019-11-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_user', '0004_location_status_bit'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default=0.0, max_length=20),
        ),
    ]
