# Generated by Django 2.2 on 2019-11-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_user', '0005_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='email_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
